config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"

  match "auth/:provider/callback", to: "sessions#create", via: :all
  post   "/login",                 to: "sessions#create"
  match "logout", to: "sessions#destroy", via: :all
  match "/auth/failure", via: :all do
    flash[:notice] = params[:message]
    redirect "/"
  end

  
  get "/meal-plan" => "meals#show"
  get "/account" => "users#show"
  get "/login" => "sessions#new"

  resources :sessions,         except: [:create, :destroy, :new]
  resources :meals,            except: :show
  resources :users,            except: [:show]
  resources :home,             only: :index
  resources :favorites,        only: :index
  resources :password_resets,  only: [:new, :create, :edit, :update]
  resources :banned_foods,     only: [:create, :destroy]
  resources :allergies,        only: [:create, :destroy]
  resources :diets,            only: [:create, :destroy]
  resources :cuisines,         only: [:create, :destroy]
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  has_many :user_banned_foods
  has_many :banned_foods, through: :user_banned_foods

  has_many :user_diets
  has_many :diets, through: :user_diets

  has_many :user_allergies
  has_many :allergies, through: :user_allergies

  has_many :user_cuisines
  has_many :cuisines, through: :user_cuisines

  has_many :meals
  
  before_save { self.email = email.downcase }
  VALID_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates_format_of :email, with: VALID_REGEX, on: :create
  validates :email, presence: true, uniqueness: true                  
  validates :user_name, presence: true

  def self.find_or_create_from_auth(data)
    user = User.find_or_create_by(provider: data.provider, 
                                  uid: data.uid)    

    user.provider = data.provider
    user.uid = data.uid
    user.user_name = data.info.name
    user.token = data.credentials.token
    user.expires_at = Time.at(data.credentials.expires_at)
    user.email = data.info.email
    user.save(validate: false)

    return user
  end

  def not_registered_with_facebook?
    provider.nil?
  end

  private

  def downcase_email
    self.email = email.downcase
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end

  def edit
    @user = current_user
  end

  def create
  	@user = User.new(user_params)
    if @user.save
      UserMailer.account_confirmation(@user).deliver_now
      sign_in
    elsif User.find_by(email: params[:user][:email])
      redirect_to :back
      flash[:alert] = "An account with that email already exists."
    else
  		redirect_to :back
  		flash[:alert] = "One of your fields is not correct."
  	end
  end

  def update
    if current_user.update(user_params)
      flash[:alert] = "Your information has been updated."
      redirect_to account_path
    else
      flash[:danger] = "You are missing some fields."
      redirect_to :back
    end
  end

  def show
  	if current_user.user_name.nil?
      flash[:danger] = "You are not authorized to access this page"
      redirect_to root_path
  	end
  end

  private
  
   def user_params
    params.require(:user).permit(:user_name, :email, :phone_number, :password, :password_confirmation)
  end
end

app/views/users/edit.html.erb
<div class="container text-center col-sm-6 col-sm-offset-3">
	<div class="row">
		<h1>Edit Your Profile</h1>

		<div class="form-group">
			<%= form_for(:user, url: user_path(@user), method: :put) do |f| %>
				<% if @user && @user.errors.any? %>
				    <div class="alert alert-danger">
				    The form contains <%= pluralize(@user.errors.count, "error") %>.
				    </div>
				    <ul>
				      <% @user.errors.full_messages.each do |msg| %>
				        <li><%= msg %></li>
				      <% end %>
				    </ul>
				<% end %>	
				<p><%= f.label :user_name, "User Name", class: 'user-form-label' %>
					 <%= f.text_field :user_name %></p>
				<p><%= f.label :email, class: 'user-form-label' %>  
					 <%= f.text_field :email %></p>
				<p><%= f.label :phone_number, "Phone Number", class: 'user-form-label' %>
					 <%= f.text_field :phone_number %></p>
				<p><%= f.submit "Submit", class: "btn btn-dark" %></p>
			<% end %>
		</div>
	</div>
</div>

app/views/users/new.html.erb
<div class="container text-center col-sm-4 col-sm-offset-4">
	<p><%= link_to image_tag("login_with_facebook.png", height: "100px"), "/auth/facebook", id: "facebook-login"  %></p>

	<h1>Create An Account</h1>

	<div class="form-group ">
		<%= form_for(:user, url: users_path, method: :post) do |f| %>
			<p><%= f.label :user_name, "User Name", class: 'user-form-label' %>
				 <%= f.text_field :user_name %></p>
			<p><%= f.label :email, class: 'user-form-label' %>  
				 <%= f.text_field :email %></p>
			<p><%= f.label :phone_number, "Phone Number", class: 'user-form-label' %>
				 <%= f.text_field :phone_number %></p>
			<p><%= f.label :password, class: 'user-form-label' %>
				 <%= f.text_field :password %></p>
			<p><%= f.label :password_confirmation, "Password Confirmation", class: 'user-form-label' %>
				 <%= f.text_field :password_confirmation %></p>
			<p><%= f.submit "Submit", class: "btn btn-dark" %></p>
		<% end %>
	</div>
</div>

app/views/users/show.html.erb
<div class="container">
	<div id="account">
	 <h1 class="text-center" id="account-header"><%= current_user.user_name %>'s Account</h1>
	</div>

	<div class="col-sm-4 col-sm-offset-4 text-center">
		<p><span class="user-profile-label">User Name:</span> 
			<span class="user-profile-field"><%= current_user.user_name %></span></p>
		<p><span class="user-profile-label">Email:</span> 
			<span class="user-profile-field"><%= current_user.email %></span></p>
			<% if current_user.phone_number %>
				<p><span class="user-profile-label">Phone Number:</span>  
					<span class="user-profile-field"><%= current_user.phone_number %></span></p>
			<% end %>
		<%= link_to "Edit My Profile", edit_user_path(current_user.id), class: "btn btn-dark" %>
	</div>
</div>