config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"

  match "auth/:provider/callback", to: "sessions#create", via: :all
  post   "/login",                 to: "sessions#create"
  match "logout", to: "sessions#destroy", via: :all
  match "/auth/failure", via: :all do
    flash[:notice] = params[:message]
    redirect "/"
  end

  
  get "/meal-plan" => "meals#show"
  get "/account" => "users#show"
  get "/login" => "sessions#new"

  resources :sessions,         except: [:create, :destroy, :new]
  resources :meals,            except: :show
  resources :users,            except: [:show]
  resources :home,             only: :index
  resources :favorites,        only: :index
  resources :password_resets,  only: [:new, :create, :edit, :update]
  resources :banned_foods,     only: [:create, :destroy]
  resources :allergies,        only: [:create, :destroy]
  resources :diets,            only: [:create, :destroy]
  resources :cuisines,         only: [:create, :destroy]
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	
  end
end

app/views/home/index.html.erb
<div class="row" id="hero-image">
	<div id="front-page-signup">
		<h1 class="front-page-text text-center">DeListcious</h1>
		<h4 class="front-page-text" id="front-page-tagline">Meal Plans in One Click</h4>
		<div class="col-xs-4 col-xs-offset-4">
			<div class="text-center btn-group">
				<%= link_to "Create an Account", new_user_path, class: "btn btn-default" %>
				<%= link_to "Log In", login_path, class: "btn btn-default" %>
			</div>
		</div>
	</div>
</div>

<div class="row"> 
	<div class="col-sm-4 front-page-description front-row">
		<div class="col-sm-3 text-center">
			<%= image_tag("white-wheat.png", height: "80", class: "text-center") %>
		</div>
		<div class="col-sm-9">
			<h4 class="text-center">Enter your dietary restrictions</h4>
		</div>
	</div>

	<div class="col-sm-4 front-page-description">
		<div class="col-sm-3 text-center">
			<%= image_tag("fork-knife-white.png", height: "80", class: "text-center") %>
		</div>
		<div class="col-sm-9">
			<h4 class="text-center">Let us know how many meals you would like</h4>
	 	</div>
	</div>

	<div class="col-sm-4 front-page-description front-row">
		<div class="col-sm-3 text-center">
			<%= image_tag("list_ingredients.png", height: "80", class: "text-center") %>
		</div>
		<div class="col-sm-9">
			<h4 class="text-center">We'll give you a meal plan and grocery list!</h4>
		</div>
	</div>
</div>