config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"

  match "auth/:provider/callback", to: "sessions#create", via: :all
  post   "/login",                 to: "sessions#create"
  match "logout", to: "sessions#destroy", via: :all
  match "/auth/failure", via: :all do
    flash[:notice] = params[:message]
    redirect "/"
  end

  
  get "/meal-plan" => "meals#show"
  get "/account" => "users#show"
  get "/login" => "sessions#new"

  resources :sessions,         except: [:create, :destroy, :new]
  resources :meals,            except: :show
  resources :users,            except: [:show]
  resources :home,             only: :index
  resources :favorites,        only: :index
  resources :password_resets,  only: [:new, :create, :edit, :update]
  resources :banned_foods,     only: [:create, :destroy]
  resources :allergies,        only: [:create, :destroy]
  resources :diets,            only: [:create, :destroy]
  resources :cuisines,         only: [:create, :destroy]
end

app/models/meal.rb
class Meal < ActiveRecord::Base
	belongs_to :user
	has_many :ingredients

	attr_reader :current_user

	def self.service
		@service ||= MealService.new(@current_user)
	end

	def self.structify_meals
		service.meals["matches"].map do |match|
			OpenStruct.new(match)
		end
	end

	def self.meals_wanted(num)
		structify_meals.sample(num)
	end

	def self.make_meals(num, current_user)
		@current_user = current_user

		meals_wanted(num).map do |meal|
			new_meal = Meal.create(
		 		name: 			 meal.recipeName,
		 		yummly_id: 	 meal.id,
		    source_name: meal.sourceDisplayName,
		    image_url: 	 meal.imageUrlsBySize.values.first,
		    user_id: 		 current_user.id
				)
			meal.ingredients.map do |ing|
				Ingredient.create(name: ing, meal_id: new_meal.id)
			end
		end
	end
end

app/controllers/meals_controller.rb
class MealsController < ApplicationController
	def show
		@meals = current_user.meals
		@ingredients = readable_ingredients(@meals)
	end

	def new
		@banned_foods = current_user.banned_foods
		@allergies = (Allergy.all - current_user.allergies	)
		@diets = Diet.all
    @cuisines = Cuisine.all

    @button_class = "btn-danger"
	end

	def create
		destroy_all_user_meals
 		@fave_num = params[:meal][:fave_num].to_i
 		@meal_num = params[:meal][:meal_num].to_i

 		@meals = Meal.make_meals(@meal_num, current_user)

 		redirect_to meal_plan_path
	end

	private
	
	def destroy_all_user_meals
		Meal.where(user_id: current_user.id).destroy_all
	end

	def readable_ingredients(meals)
		(meals.map do |meal| 
			meal.ingredients.map do |ingredient|
				ingredient.name
			end
		end).flatten.uniq.sort
	end

	def user_hatred_status(food_thing)
		if user.(food_thing.pluralize).includes?(food_thing)
			"btn-danger"
		else
			"btn-hate-it"
		end
	end
end

app/views/meals/new.html.erb
<div class="container">
	<h1 class="text-center">Plan Your Meals</h1>

	<div class="account-tabs">
		  <div class="row text-center">
		  	<h3>Foods I Avoid</h3>
		  </div>

			<div class="text-center">
			  <div id="hated-foods-list">
					<button type="button" class="btn btn-try-again" id="specific-food-header">Specific Foods</button>
					<button type="button" class="btn btn-try-again" id="allergy-header">Add An Allergy</button>
					<button type="button" class="btn btn-try-again" id="diet-header">Add A Diet</button>
					<button type="button" class="btn btn-try-again" id="cuisine-header">Ban A Cuisine</button>
			  	
					<div class="col-xs-12 hated-food hidden" id="specific-food">
						<%= render "banned_foods/new" %>
						 
				 		<div id="banned-food-list" class="text-center">
					 		<% if @banned_foods %>
								<% @banned_foods.each do |food| %>
									<button type="button" class="btn btn-danger one-banned-food" data-id="<%= food.id %>"><%= food.name %></button>
								<% end %>		
							<% end %>					
				 		</div>
				 </div>

					<div class="col-xs-12 hated-food hidden" id="allergy">
						<% @allergies.each do |allergy| %>
							<button type="button" class="btn btn-hate-it" data-id="<%= allergy.id %>">
									<%= allergy.name %></button>
						<% end %>
						<% current_user.allergies.each do |allergy| %>
							<button type="button" class="btn btn-danger" data-id="<%= allergy.id %>">
							<%= allergy.name %></button>
						<% end %>
					</div>

					<div class="col-xs-12 hated-food hidden" id="diet">
					 	<% @diets.each do |diet| %>
					 		<%if current_user.diets.include?(diet) %>
								<button type="button" class="btn btn-danger" data-id="<%= diet.id %>">
								<%= diet.name %></button>
								<% else %>
								<button type="button" class="btn btn-hate-it" data-id="<%= diet.id %>">
								<%= diet.name %></button>
							<% end %>	
						<% end %>	 	
					</div>

					<div class="col-xs-12 hated-food hidden" id="cuisine">
					 	<% @cuisines.each do |cuisine| %>
							<%if current_user.cuisines.include?(cuisine) %>
								<button type="button" class="btn btn-danger" data-id="<%= cuisine.id %>">
								<%= cuisine.name %></button>
							<% else %>
								<button type="button" class="btn btn-hate-it" data-id="<%= cuisine.id %>">
								<%= cuisine.name %></button>
							<% end %>
						<% end %>	 	
					</div>
				</div>
			</div>

				<%= form_for(:meal, url: meals_path, method: :post) do |f| %>
					<div class="row">
						<h4 class="text-center" id="meal-number">How many meals would you like? <%= image_tag("arrowdown.png", height: "20") %>
						</h4>
	 				  <div class="col-sm-2 col-sm-offset-5 hidden text-center" id="meal-number-selection">
		 				  <%= f.select :meal_num, options_for_select(1..10), class: "form-control text-center" %>
	 				  </div>
					</div>
		 			<div class="row text-center">
						 <p><%= f.submit "Get Your Meal Plan", class: "btn btn-hate-it", id: "get-plan-btn" %></p>
					</div>
				<% end %>
		</div>
	</div>
</div>

app/views/meals/show.html.erb
<div class="container">
	<div class="row">
		<h1 class="text-center one-meal">This Week's Meal Plan</h1>
	</div>

	<% @meals.each do |meal| %>
		<div class="row one-meal">
			<div class="col-sm-4 text-center">
				<div class="image-background">
					<%= image_tag(meal.image_url, height: "200") %>
				</div>
			</div>
			<div class="col-sm-6 text-left">
				<h2><%= meal.name %></h2>
				<h4>Ingredients:</h4>
				<ul>
					<% meal.ingredients.each do |ingredient| %>
						<li><%= ingredient.name %></li>
					<% end %>
				</ul>
				<p><%= link_to "Full Instructions", "http://www.yummly.com/recipe/#{meal.yummly_id}", class: "btn btn-dark" %></p>
			</div>
		</div>
	<% end %>

	<div class="text-center" id="grocery-list">
		<h2>Grocery List</h2>
			<% @ingredients.each do |ing| %>
				<%= ing %></br>
			<% end %><br>
		<!-- <button type="button" class="btn btn-dark">Export to Wunderlist</button>	 -->
	</div>
</div>